"""Initial migration

Revision ID: 983c46dbf88c
Revises: 
Create Date: 2024-08-26 16:07:17.044271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983c46dbf88c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('date_time_from', sa.DateTime(), nullable=False),
    sa.Column('date_time_to', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('date_time_from', sa.DateTime(), nullable=False),
    sa.Column('date_time_to', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_booking')
    op.drop_table('appointment')
    # ### end Alembic commands ###
